"""
repovault_reader.py — Offline Reader for Observed RepoVault Facts

Reads known RepoVault facts from local static data (observed via GITSEA UI
and BaseScan). This is NOT a live on-chain query.

This file does NOT:
  - Call any Base RPC endpoint
  - Query any wallet balance or nonce
  - Send any transaction
  - Import any wallet key
  - Connect to any network

All data is static, derived from observation of the GITSEA UI after
the "Link on Base" registration was completed by the repository owner.

The RepoVault is a GITSEA smart contract on Base. It is NOT a user wallet.
Dan-Go observing its existence is not the same as Dan-Go controlling it.

Core principle:
  "Dan-Go observes treasury context; it does not operate the treasury."

No secrets. No private keys. No wallet operations. No network. stdlib only.

Usage:
    python bridge/gitsea/treasury/runtime/repovault_reader.py
    python bridge/gitsea/treasury/runtime/repovault_reader.py --json
    python bridge/gitsea/treasury/runtime/repovault_reader.py --field repovault_address
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

_FILE_DIR = Path(__file__).parent
_TREASURY = _FILE_DIR.parent
_EXAMPLES = _TREASURY / "examples"


# ── Static observed data ──────────────────────────────────────────────────────
# These values were observed from:
#   1. GITSEA app UI after successful "Link on Base" transaction
#   2. BaseScan observation of the resulting RepoLinked event
#
# Dan-Go did NOT execute the registration transaction.
# Dan-Go does NOT have signing authority over this contract.
# Dan-Go does NOT control or operate this RepoVault.

REPOVAULT_FACTS = {
    # Repository identity
    "repo":                "olddqn/dango-mujin",
    "github_url":          "https://github.com/olddqn/dango-mujin",

    # On-chain identity
    "chain":               "Base",
    "chain_id":            8453,
    "network_rpc_note":    (
        "Dan-Go does not call the Base RPC. "
        "All on-chain data in this file is from offline observation."
    ),

    # Participants
    "owner_wallet":        "0x89b38ff776565f095b3cd46C5f35EAb27506417C",
    "owner_note": (
        "This is the repository owner's wallet address as declared in asset.toml [splits]. "
        "Dan-Go does not control this wallet. Dan-Go does not import this wallet."
    ),

    # Contract
    "repovault_address":   "0x3F9c96A429697B458Fe0a16502A050E5AB50bB00",
    "repovault_note": (
        "The RepoVault is a GITSEA smart contract on Base. "
        "It is NOT a user wallet. "
        "Dan-Go does not deploy, control, or operate this contract."
    ),

    # On-chain identifiers (from RepoLinked event)
    "repo_id":             "B93829F8829E2FFD13EF10ABA0B8442233BCF80172321B951C50E2E0C4C30D08",
    "splits_root":         "DA309748EA18E9C8C99B7FC50828251D30EB65EB1817FFF6507EC6AB5895B959",
    "repo_id_note": (
        "The repo_id is a keccak256 hash generated by GITSEA internally. "
        "Dan-Go cannot reproduce this hash (stdlib only, no keccak library)."
    ),

    # Event
    "event":               "RepoLinked",
    "observation_status":  "linked",
    "source":              "observed_basescan",
    "observed_at_note": (
        "Observed after Phase 8 asset registration failure investigation (2026-05-30). "
        "The RepoLinked event confirmed successful on-chain registration."
    ),

    # Invariants
    "moves_money":         False,
    "execution_allowed":   False,
    "hard_enforcement":    False,
    "advisory":            True,
    "authority":           "none",
    "dango_controls_vault": False,
    "dango_executes_vault": False,

    "principle": (
        "Dan-Go observes treasury context; it does not operate the treasury."
    ),
}

READABLE_FIELDS = [
    "repo", "chain", "chain_id", "owner_wallet", "repovault_address",
    "repo_id", "splits_root", "event", "observation_status", "source",
]


# ── Reader ────────────────────────────────────────────────────────────────────

def read_repovault(field: str | None = None) -> dict | str | int | bool | None:
    """
    Return the known RepoVault facts. If `field` is given, return that field only.
    """
    if field:
        return REPOVAULT_FACTS.get(field)
    return dict(REPOVAULT_FACTS)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(
        description="Read observed RepoVault facts (offline, no RPC).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This reader does NOT call Base RPC. All data is statically observed.

Available fields:
  repo, chain, chain_id, owner_wallet, repovault_address,
  repo_id, splits_root, event, observation_status, source

Examples:
  python bridge/gitsea/treasury/runtime/repovault_reader.py
  python bridge/gitsea/treasury/runtime/repovault_reader.py --json
  python bridge/gitsea/treasury/runtime/repovault_reader.py --field repovault_address
  python bridge/gitsea/treasury/runtime/repovault_reader.py --field repo_id
        """,
    )
    p.add_argument("--field", metavar="FIELD",
                   choices=READABLE_FIELDS,
                   help="Print a single field value")
    p.add_argument("--json", action="store_true", dest="json_output",
                   help="Print full JSON")
    args = p.parse_args()

    if args.field:
        val = read_repovault(args.field)
        print(val)
        return

    facts = read_repovault()

    if args.json_output:
        print(json.dumps(facts, indent=2, ensure_ascii=False))
        return

    # Default: human-readable
    print(f"\n{'='*60}")
    print(f"  RepoVault Reader: {facts['repo']}")
    print(f"{'='*60}")
    print(f"  Chain:             {facts['chain']}  (chain_id {facts['chain_id']})")
    print(f"  Owner wallet:      {facts['owner_wallet']}")
    print(f"  RepoVault:         {facts['repovault_address']}")
    print(f"  Repo ID:           {facts['repo_id'][:24]}...")
    print(f"  Splits root:       {facts['splits_root'][:24]}...")
    print(f"  Event:             {facts['event']}")
    print(f"  Status:            {facts['observation_status']}")
    print(f"  Source:            {facts['source']}")
    print(f"\n  RepoVault note:    {facts['repovault_note']}")
    print(f"\n  Dan-Go controls:   {facts['dango_controls_vault']}")
    print(f"  Dan-Go executes:   {facts['dango_executes_vault']}")
    print(f"  moves_money:       {facts['moves_money']}")
    print(f"  execution_allowed: {facts['execution_allowed']}")
    print(f"  advisory:          {facts['advisory']}")
    print(f"  authority:         {facts['authority']}")
    print(f"\n  Principle: {facts['principle']}")
    print()


if __name__ == "__main__":
    main()
