#!/usr/bin/env python3
"""
graph_export.py — dango-gitsea-bridge / su-table

Export a negotiation graph to Mermaid or plain-text format.
No external libraries required.

Usage:
  python runtime/graph_export.py --claim-id housing-001 --format mermaid
  python runtime/graph_export.py --claim-id housing-001 --format text
  python runtime/graph_export.py --claim-id housing-001 --format mermaid > examples/housing-001.graph.mmd
  python runtime/graph_export.py --list

Mermaid output can be rendered at https://mermaid.live or embedded in
GitHub markdown with triple-backtick mermaid fences.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from negotiation_graph import build_graph, list_claim_ids


# ══════════════════════════════════════════════════════════════
# MERMAID EXPORT
# ══════════════════════════════════════════════════════════════

# Node shape templates — mermaid syntax
# Each is a tuple: (open_bracket, close_bracket)
MERMAID_SHAPE = {
    "rect":       ("[", "]"),
    "round":      ("(", ")"),
    "hex":        ("{", "}"),
    "para":       ("[/", "/]"),
    "stadium":    ("([", "])"),
    "asymmetric": (">", "]"),
}

# classDef definitions — terminal-friendly ASCII colour approximations
# (Mermaid uses hex; these work on mermaid.live and GitHub)
MERMAID_CLASSDEFS = """\
  classDef claim          fill:#dbeafe,stroke:#2563eb,color:#1e3a5f
  classDef objection      fill:#ffedd5,stroke:#ea580c,color:#431407
  classDef amendment      fill:#ede9fe,stroke:#7c3aed,color:#2e1065
  classDef support        fill:#dcfce7,stroke:#16a34a,color:#14532d
  classDef escalation     fill:#fef3c7,stroke:#d97706,color:#451a03
  classDef correction     fill:#f3f4f6,stroke:#6b7280,color:#111827
  classDef withdrawal     fill:#f1f5f9,stroke:#64748b,color:#0f172a
  classDef contrib        fill:#f5f3ff,stroke:#8b5cf6,color:#2e1065
  classDef contribBlocked fill:#fee2e2,stroke:#dc2626,color:#450a0a
  classDef execution      fill:#ede7f6,stroke:#7c3aed,color:#2e1065
  classDef feedbackOk     fill:#dcfce7,stroke:#15803d,color:#14532d
  classDef feedbackPartial fill:#fef9c3,stroke:#ca8a04,color:#422006
  classDef feedbackFail   fill:#fee2e2,stroke:#dc2626,color:#450a0a
  classDef feedbackUnexpected fill:#fff7ed,stroke:#c2410c,color:#431407
  classDef danger         fill:#7f1d1d,stroke:#450a0a,color:#fef2f2\
"""

EDGE_ARROW = {
    "temporal":   "-->",
    "danger":     "-->",
    "correction": "-.->",
    "hash_chain": "-.->",
}

EDGE_LABEL = {
    "correction": "|corrects|",
    "hash_chain": "|chain|",
}


def _sanitize_label(label: str) -> str:
    """Escape double-quotes and newlines for mermaid node labels."""
    return label.replace('"', "'").replace("\n", "<br/>")


def _mermaid_node_line(node: dict) -> str:
    shape = node.get("shape", "rect")
    op, cl = MERMAID_SHAPE.get(shape, ("[", "]"))
    label  = _sanitize_label(node["label"])
    nid    = node["id"]
    cls    = node.get("style", "default")
    ts     = node["timestamp"][:16].replace("T", " ")  # "2026-05-23 16:14"
    full   = f'{label}<br/><small>{ts}</small>'
    return f'  {nid}{op}"{full}"{cl}:::{cls}'


def _mermaid_edge_line(edge: dict) -> str:
    kind   = edge["kind"]
    arrow  = EDGE_ARROW.get(kind, "-->")
    elabel = EDGE_LABEL.get(kind, "")
    if elabel:
        return f'  {edge["from"]} {arrow} {elabel} {edge["to"]}'
    return f'  {edge["from"]} {arrow} {edge["to"]}'


def export_mermaid(graph: dict) -> str:
    claim_id = graph["claim_id"]
    nodes    = graph["nodes"]
    edges    = graph["edges"]
    meta     = graph.get("meta", {})

    if not nodes:
        return f"%% No events found for claim_id: {claim_id}\nflowchart TD\n  empty[\"(no events)\"]"

    lines: list[str] = []

    # Header comment
    lines.append(f"%% Negotiation Graph: {claim_id}")
    lines.append(f"%% Generated by dango-gitsea-bridge / graph_export.py")
    lines.append(f"%% Events: {meta.get('total_events', '?')}  |  "
                 f"Final: {meta.get('final_result', 'in progress')}")
    if meta.get("has_dignity_violation"):
        lines.append("%% ⚠ DIGNITY VIOLATION DETECTED — see red node")
    lines.append("")

    lines.append("flowchart TD")

    # Class definitions
    lines.append(MERMAID_CLASSDEFS)
    lines.append("")

    # Node declarations
    lines.append("  %% ── Nodes ─────────────────────────────")
    for node in nodes:
        lines.append(_mermaid_node_line(node))
    lines.append("")

    # Edges
    lines.append("  %% ── Edges ─────────────────────────────")
    for edge in edges:
        lines.append(_mermaid_edge_line(edge))

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# TEXT EXPORT
# ══════════════════════════════════════════════════════════════

ICON = {
    "claim":            "📋",
    "objection":        "⚡",
    "amendment":        "✏",
    "support":          "✓",
    "escalation":       "⚠",
    "correction":       "↩",
    "withdrawal":       "↰",
    "contrib":          "→",
    "contribBlocked":   "✗",
    "execution":        "▶",
    "feedbackOk":       "✓",
    "feedbackPartial":  "◑",
    "feedbackFail":     "✗",
    "feedbackUnexpected":"⚡",
    "danger":           "🛑",
    "default":          "•",
}

EDGE_TEXT = {
    "temporal":   "│",
    "danger":     "│",
    "correction": "╌╌ corrects ╌╌",
    "hash_chain": "╌╌ chain ╌╌",
}


def export_text(graph: dict) -> str:
    claim_id = graph["claim_id"]
    nodes    = graph["nodes"]
    edges    = graph["edges"]
    meta     = graph.get("meta", {})

    if not nodes:
        return f"CLAIM {claim_id}\n  (no events found)"

    lines: list[str] = []

    lines.append("=" * 60)
    lines.append(f"NEGOTIATION GRAPH — {claim_id}")
    lines.append("=" * 60)
    lines.append(f"Total events:  {meta.get('total_events', '?')}")
    lines.append(f"Tables:        {', '.join(meta.get('tables_involved', []))}")
    lines.append(f"Final result:  {meta.get('final_result', 'in progress') or 'in progress'}")
    if meta.get("has_dignity_violation"):
        lines.append("⚠ DIGNITY VIOLATION DETECTED")
    lines.append("")

    # Build adjacency for edge labels on non-temporal edges
    correction_edges: dict[str, list[str]] = {}  # src_id → [dst_id, ...]
    for edge in edges:
        if edge["kind"] in ("correction", "hash_chain"):
            correction_edges.setdefault(edge["from"], []).append(
                (edge["to"], edge["kind"])
            )

    lines.append("── EVENT TIMELINE ──")
    lines.append("")

    id_to_node = {n["id"]: n for n in nodes}

    for i, node in enumerate(nodes):
        nid   = node["id"]
        icon  = ICON.get(node["style"], "•")
        ts    = node["timestamp"][:19].replace("T", " ")
        label = node["label"].replace("\n", " / ")
        table = node["table"]

        lines.append(f"  {i+1:2d}. {icon} [{table}] {label}")
        lines.append(f"       {ts}")

        # Speaker or contributor
        meta_n = node.get("meta", {})
        actor = meta_n.get("speaker") or meta_n.get("contributor") or meta_n.get("contributor_id")
        if actor:
            lines.append(f"       speaker: {actor}")

        # Dignity flags
        if meta_n.get("dignity_violation"):
            lines.append("       ⚠ DIGNITY VIOLATION — automated processing halted")
        if meta_n.get("requires_human_review"):
            lines.append("       ⚠ requires human review")

        # Correction cross-references
        if nid in correction_edges:
            for (dst_id, kind) in correction_edges[nid]:
                dst_node = id_to_node.get(dst_id)
                if dst_node:
                    lines.append(f"       {EDGE_TEXT.get(kind, '?')} → {dst_node['label'][:50]}")

        # Connector to next node
        if i < len(nodes) - 1:
            lines.append("       │")

    lines.append("")

    # Summary of edges
    corr_edges = [e for e in edges if e["kind"] == "correction"]
    if corr_edges:
        lines.append("── CORRECTION EDGES ──")
        for e in corr_edges:
            src = id_to_node.get(e["from"], {})
            dst = id_to_node.get(e["to"],   {})
            lines.append(f"  {src.get('id','?')} ({src.get('label','?')[:32]})")
            lines.append(f"    ╌╌ corrects ╌╌→ {dst.get('id','?')} ({dst.get('label','?')[:32]})")
        lines.append("")

    lines.append("=" * 60)
    final = meta.get("final_result", "")
    if final == "success":
        lines.append("OUTCOME: ✓ SUCCESS — Claim fully realized.")
    elif final == "partial_success":
        lines.append("OUTCOME: ◑ PARTIAL SUCCESS — Claim partially realized.")
    elif final == "failed":
        lines.append("OUTCOME: ✗ FAILED — Claim not realized.")
    elif final == "dignity_violation_detected":
        lines.append("OUTCOME: 🛑 DIGNITY VIOLATION — requires immediate human review.")
    elif final == "unexpected_outcome":
        lines.append("OUTCOME: ⚡ UNEXPECTED — outcome differed from claim.")
    else:
        lines.append("OUTCOME: ⏳ IN PROGRESS — no reality feedback yet.")
    lines.append("=" * 60)

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Export a su-table negotiation graph to mermaid or text",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python runtime/graph_export.py --claim-id housing-001 --format text
  python runtime/graph_export.py --claim-id housing-001 --format mermaid
  python runtime/graph_export.py --claim-id housing-001 --format mermaid > examples/housing-001.graph.mmd
  python runtime/graph_export.py --list
        """,
    )
    p.add_argument("--claim-id",  metavar="ID",
                   help="Claim ID to visualize")
    p.add_argument("--format",    choices=["mermaid", "text"], default="text",
                   help="Output format (default: text)")
    p.add_argument("--list",      action="store_true",
                   help="List all available claim_ids in the su-table")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.list:
        ids = list_claim_ids()
        if not ids:
            print("No claim_ids found in su-table.")
        else:
            print("Available claim_ids in su-table:")
            for cid in ids:
                print(f"  {cid}")
        return

    if not args.claim_id:
        print("Error: --claim-id is required (or use --list)", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(args.claim_id)

    if not graph["nodes"]:
        print(f"No events found for claim_id: {args.claim_id}", file=sys.stderr)
        sys.exit(1)

    match args.format:
        case "mermaid":
            print(export_mermaid(graph))
        case "text":
            print(export_text(graph))


if __name__ == "__main__":
    main()
