#!/usr/bin/env python3
"""
graph_export.py — dango-gitsea-bridge / su-table

Export a negotiation graph to Mermaid, plain-text, or HTML format.
No external libraries required. No CDN. No network calls.

Usage:
  python runtime/graph_export.py --claim-id housing-001 --format text
  python runtime/graph_export.py --claim-id housing-001 --format mermaid
  python runtime/graph_export.py --claim-id housing-001 --format html --output examples/housing-001.graph.html
  python runtime/graph_export.py --claim-id housing-001 --format mermaid > examples/housing-001.graph.mmd
  python runtime/graph_export.py --list

HTML preview is local-only. It does not load any external scripts or stylesheets.
Mermaid code is displayed as a copyable source block with instructions to paste
into https://mermaid.live for rendering.
"""

import argparse
import html as html_escape_mod
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from negotiation_graph import build_graph, list_claim_ids


# ══════════════════════════════════════════════════════════════
# MERMAID EXPORT
# ══════════════════════════════════════════════════════════════

MERMAID_SHAPE = {
    "rect":       ("[", "]"),
    "round":      ("(", ")"),
    "hex":        ("{", "}"),
    "para":       ("[/", "/]"),
    "stadium":    ("([", "])"),
    "asymmetric": (">", "]"),
}

MERMAID_CLASSDEFS = """\
  classDef claim          fill:#dbeafe,stroke:#2563eb,color:#1e3a5f
  classDef objection      fill:#ffedd5,stroke:#ea580c,color:#431407
  classDef amendment      fill:#ede9fe,stroke:#7c3aed,color:#2e1065
  classDef support        fill:#dcfce7,stroke:#16a34a,color:#14532d
  classDef escalation     fill:#fef3c7,stroke:#d97706,color:#451a03
  classDef correction     fill:#f3f4f6,stroke:#6b7280,color:#111827
  classDef withdrawal     fill:#f1f5f9,stroke:#64748b,color:#0f172a
  classDef contrib        fill:#f5f3ff,stroke:#8b5cf6,color:#2e1065
  classDef contribBlocked fill:#fee2e2,stroke:#dc2626,color:#450a0a
  classDef execution      fill:#ede7f6,stroke:#7c3aed,color:#2e1065
  classDef feedbackOk     fill:#dcfce7,stroke:#15803d,color:#14532d
  classDef feedbackPartial fill:#fef9c3,stroke:#ca8a04,color:#422006
  classDef feedbackFail   fill:#fee2e2,stroke:#dc2626,color:#450a0a
  classDef feedbackUnexpected fill:#fff7ed,stroke:#c2410c,color:#431407
  classDef danger         fill:#7f1d1d,stroke:#450a0a,color:#fef2f2\
"""

EDGE_ARROW = {
    "temporal":   "-->",
    "danger":     "-->",
    "correction": "-.->",
    "hash_chain": "-.->",
}

EDGE_LABEL = {
    "correction": "|corrects|",
    "hash_chain": "|chain|",
}


def _sanitize_label(label: str) -> str:
    return label.replace('"', "'").replace("\n", "<br/>")


def _sig_suffix(node: dict) -> str:
    """Return ' ✓sig' if the node has a valid mock signature, else ''."""
    sig_status = node.get("meta", {}).get("signature_status", "")
    if sig_status == "mock_valid":
        return " ✓sig"
    return ""


def _mermaid_node_line(node: dict) -> str:
    shape = node.get("shape", "rect")
    op, cl = MERMAID_SHAPE.get(shape, ("[", "]"))
    label  = _sanitize_label(node["label"]) + _sig_suffix(node)
    nid    = node["id"]
    cls    = node.get("style", "default")
    ts     = node["timestamp"][:16].replace("T", " ")
    full   = f'{label}<br/><small>{ts}</small>'
    return f'  {nid}{op}"{full}"{cl}:::{cls}'


def _mermaid_edge_line(edge: dict) -> str:
    kind   = edge["kind"]
    arrow  = EDGE_ARROW.get(kind, "-->")
    elabel = EDGE_LABEL.get(kind, "")
    if elabel:
        return f'  {edge["from"]} {arrow} {elabel} {edge["to"]}'
    return f'  {edge["from"]} {arrow} {edge["to"]}'


def export_mermaid(graph: dict) -> str:
    claim_id = graph["claim_id"]
    nodes    = graph["nodes"]
    edges    = graph["edges"]
    meta     = graph.get("meta", {})

    if not nodes:
        return f"%% No events found for claim_id: {claim_id}\nflowchart TD\n  empty[\"(no events)\"]"

    lines: list[str] = []
    lines.append(f"%% Negotiation Graph: {claim_id}")
    lines.append(f"%% Generated by dango-gitsea-bridge / graph_export.py")
    lines.append(f"%% Events: {meta.get('total_events', '?')}  |  "
                 f"Final: {meta.get('final_result', 'in progress')}")
    if meta.get("has_dignity_violation"):
        lines.append("%% ⚠ DIGNITY VIOLATION DETECTED — see red node")
    lines.append("")
    lines.append("flowchart TD")
    lines.append(MERMAID_CLASSDEFS)
    lines.append("")
    lines.append("  %% ── Nodes ─────────────────────────────")
    for node in nodes:
        lines.append(_mermaid_node_line(node))
    lines.append("")
    lines.append("  %% ── Edges ─────────────────────────────")
    for edge in edges:
        lines.append(_mermaid_edge_line(edge))

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# TEXT EXPORT
# ══════════════════════════════════════════════════════════════

ICON = {
    "claim":             "📋",
    "objection":         "⚡",
    "amendment":         "✏",
    "support":           "✓",
    "escalation":        "⚠",
    "correction":        "↩",
    "withdrawal":        "↰",
    "contrib":           "→",
    "contribBlocked":    "✗",
    "execution":         "▶",
    "feedbackOk":        "✓",
    "feedbackPartial":   "◑",
    "feedbackFail":      "✗",
    "feedbackUnexpected":"⚡",
    "danger":            "🛑",
    "default":           "•",
}

EDGE_TEXT = {
    "temporal":   "│",
    "danger":     "│",
    "correction": "╌╌ corrects ╌╌",
    "hash_chain": "╌╌ chain ╌╌",
}


def export_text(graph: dict) -> str:
    claim_id = graph["claim_id"]
    nodes    = graph["nodes"]
    edges    = graph["edges"]
    meta     = graph.get("meta", {})

    if not nodes:
        return f"CLAIM {claim_id}\n  (no events found)"

    lines: list[str] = []
    lines.append("=" * 60)
    lines.append(f"NEGOTIATION GRAPH — {claim_id}")
    lines.append("=" * 60)
    lines.append(f"Total events:  {meta.get('total_events', '?')}")
    lines.append(f"Tables:        {', '.join(meta.get('tables_involved', []))}")
    lines.append(f"Final result:  {meta.get('final_result', 'in progress') or 'in progress'}")
    if meta.get("has_dignity_violation"):
        lines.append("⚠ DIGNITY VIOLATION DETECTED")
    lines.append("")

    correction_edges: dict[str, list] = {}
    for edge in edges:
        if edge["kind"] in ("correction", "hash_chain"):
            correction_edges.setdefault(edge["from"], []).append(
                (edge["to"], edge["kind"])
            )

    lines.append("── EVENT TIMELINE ──")
    lines.append("")
    id_to_node = {n["id"]: n for n in nodes}

    for i, node in enumerate(nodes):
        nid   = node["id"]
        icon  = ICON.get(node["style"], "•")
        ts    = node["timestamp"][:19].replace("T", " ")
        label = node["label"].replace("\n", " / ")
        table = node["table"]

        lines.append(f"  {i+1:2d}. {icon} [{table}] {label}")
        lines.append(f"       {ts}")

        meta_n = node.get("meta", {})
        actor = meta_n.get("speaker") or meta_n.get("contributor") or meta_n.get("contributor_id")
        if actor:
            lines.append(f"       speaker: {actor}")

        # Signature status line
        sig_status = meta_n.get("signature_status", "")
        if sig_status:
            sig_icons = {
                "mock_valid":                "✓ [signature: mock_valid]",
                "unsigned":                  "○ [signature: unsigned]",
                "mock_invalid":              "✗ [signature: mock_invalid]",
                "unsupported_signature_type":"? [signature: unsupported]",
            }
            signer = meta_n.get("signer_did", "")
            sig_line = sig_icons.get(sig_status, f"? [signature: {sig_status}]")
            if signer and sig_status == "mock_valid":
                sig_line += f"  signer: {signer}"
            lines.append(f"       {sig_line}")

        if meta_n.get("dignity_violation"):
            lines.append("       ⚠ DIGNITY VIOLATION — automated processing halted")
        if meta_n.get("requires_human_review"):
            lines.append("       ⚠ requires human review")

        if nid in correction_edges:
            for (dst_id, kind) in correction_edges[nid]:
                dst_node = id_to_node.get(dst_id)
                if dst_node:
                    lines.append(f"       {EDGE_TEXT.get(kind, '?')} → {dst_node['label'][:50]}")

        if i < len(nodes) - 1:
            lines.append("       │")

    lines.append("")

    corr_edges = [e for e in edges if e["kind"] == "correction"]
    if corr_edges:
        lines.append("── CORRECTION EDGES ──")
        for e in corr_edges:
            src = id_to_node.get(e["from"], {})
            dst = id_to_node.get(e["to"],   {})
            lines.append(f"  {src.get('id','?')} ({src.get('label','?')[:32]})")
            lines.append(f"    ╌╌ corrects ╌╌→ {dst.get('id','?')} ({dst.get('label','?')[:32]})")
        lines.append("")

    lines.append("=" * 60)
    final = meta.get("final_result", "")
    if final == "success":
        lines.append("OUTCOME: ✓ SUCCESS — Claim fully realized.")
    elif final == "partial_success":
        lines.append("OUTCOME: ◑ PARTIAL SUCCESS — Claim partially realized.")
    elif final == "failed":
        lines.append("OUTCOME: ✗ FAILED — Claim not realized.")
    elif final == "dignity_violation_detected":
        lines.append("OUTCOME: 🛑 DIGNITY VIOLATION — requires immediate human review.")
    elif final == "unexpected_outcome":
        lines.append("OUTCOME: ⚡ UNEXPECTED — outcome differed from claim.")
    else:
        lines.append("OUTCOME: ⏳ IN PROGRESS — no reality feedback yet.")
    lines.append("=" * 60)

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# HTML EXPORT
# ══════════════════════════════════════════════════════════════

# Style class → CSS class name used in HTML
_HTML_STYLE_CLASS = {
    "claim":             "ev-claim",
    "objection":         "ev-objection",
    "amendment":         "ev-amendment",
    "support":           "ev-support",
    "escalation":        "ev-escalation",
    "correction":        "ev-correction",
    "withdrawal":        "ev-withdrawal",
    "contrib":           "ev-contrib",
    "contribBlocked":    "ev-contrib-blocked",
    "execution":         "ev-execution",
    "feedbackOk":        "ev-feedback-ok",
    "feedbackPartial":   "ev-feedback-partial",
    "feedbackFail":      "ev-feedback-fail",
    "feedbackUnexpected":"ev-feedback-unexpected",
    "danger":            "ev-danger",
    "default":           "ev-default",
}

# Accent colours for the timeline pill badges
_BADGE_STYLE = {
    "claim":             "background:#1d4ed8;color:#eff6ff",
    "objection":         "background:#c2410c;color:#fff7ed",
    "amendment":         "background:#6d28d9;color:#ede9fe",
    "support":           "background:#15803d;color:#dcfce7",
    "escalation":        "background:#b45309;color:#fef3c7",
    "correction":        "background:#4b5563;color:#f3f4f6",
    "withdrawal":        "background:#475569;color:#f1f5f9",
    "contrib":           "background:#7c3aed;color:#f5f3ff",
    "contribBlocked":    "background:#991b1b;color:#fee2e2",
    "execution":         "background:#065f46;color:#d1fae5",
    "feedbackOk":        "background:#166534;color:#dcfce7",
    "feedbackPartial":   "background:#92400e;color:#fef3c7",
    "feedbackFail":      "background:#7f1d1d;color:#fee2e2",
    "feedbackUnexpected":"background:#9a3412;color:#fff7ed",
    "danger":            "background:#450a0a;color:#fca5a5",
    "default":           "background:#374151;color:#d1d5db",
}

_INLINE_CSS = """
:root {
  --bg:        #0d0d0d;
  --surface:   #141414;
  --surface2:  #1c1c1c;
  --border:    #2a2a2a;
  --text:      #e2e8f0;
  --muted:     #64748b;
  --accent:    #7c3aed;
  --cyan:      #22d3ee;
  --green:     #4ade80;
  --amber:     #fbbf24;
  --red:       #f87171;
  --violet:    #c084fc;
  --mono:      'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
  --sans:      system-ui, -apple-system, sans-serif;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  background: var(--bg);
  color: var(--text);
  font-family: var(--sans);
  font-size: 14px;
  line-height: 1.6;
  padding: 0 0 4rem 0;
}

.page-header {
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 1.5rem 2rem;
  display: flex;
  align-items: baseline;
  gap: 1rem;
  flex-wrap: wrap;
}
.page-header h1 {
  font-size: 1.25rem;
  font-weight: 700;
  font-family: var(--mono);
  color: var(--cyan);
  letter-spacing: -0.02em;
}
.page-header .subtitle {
  color: var(--muted);
  font-size: 0.85rem;
}
.warn-banner {
  background: #450a0a;
  border-bottom: 2px solid #f87171;
  color: #fca5a5;
  padding: 0.6rem 2rem;
  font-size: 0.9rem;
  font-weight: 600;
}

.container { max-width: 1100px; margin: 0 auto; padding: 2rem; }

section { margin-bottom: 2.5rem; }

h2 {
  font-family: var(--mono);
  font-size: 0.8rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.12em;
  color: var(--muted);
  margin-bottom: 1rem;
  padding-bottom: 0.4rem;
  border-bottom: 1px solid var(--border);
}

/* ── Summary cards ──────────────────────────────── */
.summary-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 1rem;
}
.stat-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 1rem;
}
.stat-card .val {
  font-size: 2rem;
  font-weight: 700;
  font-family: var(--mono);
  color: var(--cyan);
  line-height: 1;
}
.stat-card .lbl {
  color: var(--muted);
  font-size: 0.75rem;
  margin-top: 0.25rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}
.stat-card.danger .val { color: var(--red); }
.stat-card.good   .val { color: var(--green); }
.stat-card.amber  .val { color: var(--amber); }

/* ── Timeline ───────────────────────────────────── */
.timeline { list-style: none; }
.tl-item {
  display: flex;
  gap: 1rem;
  padding: 0.8rem 0;
  border-bottom: 1px solid var(--border);
  position: relative;
}
.tl-item:last-child { border-bottom: none; }
.tl-index {
  font-family: var(--mono);
  color: var(--muted);
  font-size: 0.75rem;
  width: 2rem;
  flex-shrink: 0;
  padding-top: 0.15rem;
  text-align: right;
}
.tl-body { flex: 1; }
.tl-badge {
  display: inline-block;
  border-radius: 4px;
  padding: 0.15rem 0.55rem;
  font-size: 0.7rem;
  font-family: var(--mono);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  margin-right: 0.4rem;
}
.tl-label {
  font-size: 0.9rem;
  font-weight: 500;
  color: var(--text);
}
.tl-meta {
  margin-top: 0.3rem;
  color: var(--muted);
  font-size: 0.78rem;
  font-family: var(--mono);
}
.tl-meta span { margin-right: 1.2rem; }
.tl-edge {
  margin-top: 0.3rem;
  font-size: 0.75rem;
  color: var(--violet);
  font-family: var(--mono);
}
.tl-danger-flag {
  margin-top: 0.4rem;
  color: var(--red);
  font-size: 0.8rem;
  font-weight: 600;
}

.ev-danger    .tl-label { color: var(--red); }
.ev-correction .tl-label { color: var(--violet); }
.ev-contrib   .tl-label { color: var(--cyan); }
.ev-execution .tl-label { color: var(--green); }
.ev-feedback-partial .tl-label { color: var(--amber); }

/* ── Mermaid block ──────────────────────────────── */
.mermaid-wrap {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  overflow: hidden;
}
.mermaid-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.6rem 1rem;
  border-bottom: 1px solid var(--border);
  background: var(--surface2);
}
.mermaid-toolbar .toolbar-left {
  font-size: 0.75rem;
  color: var(--muted);
  font-family: var(--mono);
}
.copy-btn {
  background: var(--accent);
  color: #fff;
  border: none;
  border-radius: 4px;
  padding: 0.3rem 0.8rem;
  font-size: 0.75rem;
  font-family: var(--mono);
  cursor: pointer;
  transition: background 0.15s;
}
.copy-btn:hover  { background: #6d28d9; }
.copy-btn.copied { background: #15803d; }
.mermaid-hint {
  padding: 0.5rem 1rem;
  font-size: 0.75rem;
  color: var(--muted);
  background: var(--surface2);
  border-bottom: 1px solid var(--border);
}
.mermaid-hint a {
  color: var(--cyan);
  text-decoration: none;
}
.mermaid-hint a:hover { text-decoration: underline; }
pre.mermaid-src {
  padding: 1rem;
  font-family: var(--mono);
  font-size: 0.78rem;
  line-height: 1.5;
  color: #94a3b8;
  overflow-x: auto;
  white-space: pre;
  background: transparent;
}

/* ── Event table ────────────────────────────────── */
.event-table-wrap { overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.78rem;
  font-family: var(--mono);
}
th {
  background: var(--surface2);
  color: var(--muted);
  text-align: left;
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid var(--border);
  font-weight: 600;
  white-space: nowrap;
  text-transform: uppercase;
  font-size: 0.68rem;
  letter-spacing: 0.06em;
}
td {
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid var(--border);
  vertical-align: top;
  color: var(--text);
  word-break: break-all;
}
tr:hover td { background: var(--surface); }
.td-hash { color: var(--muted); font-size: 0.7rem; }
.td-type { font-weight: 600; }
.row-danger td { color: var(--red); }
.row-correction td { color: var(--violet); }

/* ── Integrity notes ────────────────────────────── */
.integrity-block {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 1rem 1.25rem;
  font-family: var(--mono);
  font-size: 0.8rem;
}
.integrity-block .ok   { color: var(--green); }
.integrity-block .warn { color: var(--amber); }
.integrity-block .err  { color: var(--red); }
.integrity-item { margin-bottom: 0.4rem; }

/* ── Signature badges ───────────────────────────── */
.sig-badge {
  display: inline-block;
  border-radius: 3px;
  padding: 0.1rem 0.45rem;
  font-size: 0.67rem;
  font-family: var(--mono);
  font-weight: 700;
  letter-spacing: 0.04em;
  vertical-align: middle;
  margin-left: 0.4rem;
}
.sig-valid    { background:#14532d; color:#86efac; }
.sig-unsigned { background:#1c1c1c; color:#64748b; border:1px solid #2a2a2a; }
.sig-invalid  { background:#450a0a; color:#fca5a5; }
.sig-unsup    { background:#1c1f2b; color:#818cf8; }

/* ── Footer ─────────────────────────────────────── */
.page-footer {
  margin-top: 3rem;
  padding: 1rem 2rem;
  border-top: 1px solid var(--border);
  color: var(--muted);
  font-size: 0.72rem;
  font-family: var(--mono);
}
"""

_COPY_SCRIPT = """
function copyMermaid() {
  var src = document.getElementById('mermaid-source').textContent;
  var btn = document.getElementById('copy-btn');
  if (navigator && navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(src).then(function() {
      btn.textContent = '✓ Copied';
      btn.classList.add('copied');
      setTimeout(function(){ btn.textContent = 'Copy'; btn.classList.remove('copied'); }, 2000);
    }).catch(function() { fallbackCopy(src, btn); });
  } else {
    fallbackCopy(src, btn);
  }
}
function fallbackCopy(text, btn) {
  var ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.focus(); ta.select();
  try {
    document.execCommand('copy');
    btn.textContent = '✓ Copied';
    btn.classList.add('copied');
    setTimeout(function(){ btn.textContent = 'Copy'; btn.classList.remove('copied'); }, 2000);
  } catch(e) {
    btn.textContent = 'Select & copy manually';
  }
  document.body.removeChild(ta);
}
"""


def _h(s: str) -> str:
    """HTML-escape a string."""
    return html_escape_mod.escape(str(s))


def _short_hash(h: str) -> str:
    return h[:12] + "…" if len(h) >= 12 else h


def _actor(node: dict) -> str:
    m = node.get("meta", {})
    a = m.get("speaker") or m.get("contributor") or m.get("contributor_id") or ""
    if len(a) > 28:
        a = a[:12] + "…" + a[-8:]
    return a


def _summary_line(node: dict) -> str:
    """One-line human summary of the node for the event table."""
    et = node.get("event_type", "")
    m  = node.get("meta", {})
    for key in ("reason", "proposed_amendment", "notes", "note", "correction_reason"):
        val = m.get(key)
        if val:
            s = str(val)
            return s[:80] + "…" if len(s) > 80 else s
    result = m.get("result", "")
    if result:
        return f"result: {result}"
    return node.get("label", "").replace("\n", " ")[:80]


def _corrects_id(node: dict, hash_to_id: dict[str, str]) -> str:
    h = node.get("meta", {}).get("corrects_event_hash", "")
    if h and h in hash_to_id:
        return hash_to_id[h]
    return ""


def export_html(graph: dict) -> str:
    claim_id = graph["claim_id"]
    nodes    = graph["nodes"]
    edges    = graph["edges"]
    meta     = graph.get("meta", {})

    # ── Pre-compute helpers ──────────────────────────────────
    hash_to_id   = {n["event_hash"]: n["id"] for n in nodes if n.get("event_hash")}
    id_to_node   = {n["id"]: n for n in nodes}
    mermaid_src  = export_mermaid(graph)

    total        = meta.get("total_events", len(nodes))
    final_result = meta.get("final_result", "") or "in progress"
    corr_count   = sum(1 for n in nodes if n["event_type"] == "correction")
    contrib_count= sum(1 for n in nodes if "contrib" in n.get("style", ""))
    danger_count  = sum(1 for n in nodes if n.get("style") == "danger")
    corr_edges    = [e for e in edges if e["kind"] == "correction"]
    chain_edges   = [e for e in edges if e["kind"] == "hash_chain"]
    signed_preview= sum(1 for n in nodes if n.get("meta",{}).get("signature_status") == "mock_valid")

    # outgoing correction/chain edges per node
    out_special: dict[str, list] = {}
    for e in edges:
        if e["kind"] in ("correction", "hash_chain"):
            out_special.setdefault(e["from"], []).append(e)

    gen_ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── Helper: timeline items ───────────────────────────────
    def tl_item(i: int, node: dict) -> str:
        style  = node.get("style", "default")
        css    = _HTML_STYLE_CLASS.get(style, "ev-default")
        badge  = _BADGE_STYLE.get(style, "background:#374151;color:#d1d5db")
        et     = node["event_type"].replace("_", " ")
        ts     = node["timestamp"][:19].replace("T", " ")
        label  = _h(node["label"].replace("\n", " / "))
        actor  = _h(_actor(node))
        table  = _h(node["table"])
        m      = node.get("meta", {})
        nid    = node["id"]

        sig_status = m.get("signature_status", "")
        signer_did = m.get("signer_did", "")
        sig_badge_html = ""
        if sig_status == "mock_valid":
            sig_badge_html = '<span class="sig-badge sig-valid" title="mock_valid — signed">✓ sig</span>'
        elif sig_status == "unsigned":
            sig_badge_html = '<span class="sig-badge sig-unsigned" title="unsigned">unsigned</span>'
        elif sig_status == "mock_invalid":
            sig_badge_html = '<span class="sig-badge sig-invalid" title="mock_invalid — tampered?">✗ sig</span>'
        elif sig_status == "unsupported_signature_type":
            sig_badge_html = '<span class="sig-badge sig-unsup" title="unsupported signature type">? sig</span>'

        parts = [
            f'<li class="tl-item {_h(css)}">',
            f'  <span class="tl-index">{i}</span>',
            f'  <div class="tl-body">',
            f'    <span class="tl-badge" style="{_h(badge)}">{_h(et)}</span>',
            f'    <span class="tl-label">{label}</span>',
            f'    {sig_badge_html}' if sig_badge_html else "",
            f'    <div class="tl-meta">',
            f'      <span>🗄 {table}</span>',
        ]
        if actor:
            parts.append(f'      <span>👤 {actor}</span>')
        if sig_status == "mock_valid" and signer_did:
            did_short = signer_did[:24] + "…" if len(signer_did) > 24 else signer_did
            parts.append(f'      <span title="{_h(signer_did)}">🔑 {_h(did_short)}</span>')
        parts.append(f'      <span>🕐 {_h(ts)}</span>')
        parts.append(f'    </div>')

        # Out-edges (correction / chain)
        if nid in out_special:
            for e in out_special[nid]:
                dst = id_to_node.get(e["to"])
                if dst:
                    kind_lbl = "corrects →" if e["kind"] == "correction" else "chain →"
                    dst_lbl  = _h(dst["label"].replace("\n", " ")[:48])
                    parts.append(f'    <div class="tl-edge">╌╌ {_h(kind_lbl)} {dst_lbl}</div>')

        # Dignity flags
        if m.get("dignity_violation"):
            parts.append('    <div class="tl-danger-flag">🛑 DIGNITY VIOLATION — automated processing halted</div>')
        if m.get("requires_human_review") and not m.get("dignity_violation"):
            parts.append('    <div class="tl-danger-flag" style="color:var(--amber)">⚠ requires human review</div>')

        parts += ["  </div>", "</li>"]
        return "\n".join(parts)

    # Signature badge HTML for table cells
    _SIG_CELL = {
        "mock_valid":                '<span class="sig-badge sig-valid">✓ mock_valid</span>',
        "unsigned":                  '<span class="sig-badge sig-unsigned">unsigned</span>',
        "mock_invalid":              '<span class="sig-badge sig-invalid">✗ invalid</span>',
        "unsupported_signature_type":'<span class="sig-badge sig-unsup">? unsupported</span>',
    }

    # ── Helper: event table rows ─────────────────────────────
    def table_row(i: int, node: dict) -> str:
        style   = node.get("style", "default")
        row_cls = ""
        if style == "danger":
            row_cls = "row-danger"
        elif style == "correction":
            row_cls = "row-correction"
        eh  = node.get("event_hash", "")
        prev_nid  = f"n{i-2}" if i > 1 else ""  # n0-based, i is 1-based display
        prev_node = id_to_node.get(prev_nid, {})
        prev_hash = prev_node.get("event_hash", "") if prev_node else ""
        corrects_nid = _corrects_id(node, hash_to_id)
        summary = _h(_summary_line(node))
        m = node.get("meta", {})
        sig_status = m.get("signature_status", "")
        signer_did = m.get("signer_did", "")
        sig_cell   = _SIG_CELL.get(sig_status, "")
        did_short  = (signer_did[:20] + "…") if len(signer_did) > 20 else signer_did

        return (
            f'<tr class="{row_cls}">'
            f'<td class="td-hash">{_h(node["id"])}</td>'
            f'<td>{_h(node["table"])}</td>'
            f'<td class="td-type">{_h(node["event_type"])}</td>'
            f'<td>{_h(_actor(node))}</td>'
            f'<td class="td-hash">{_h(node["timestamp"][:19].replace("T"," "))}</td>'
            f'<td>{summary}</td>'
            f'<td>{sig_cell}</td>'
            f'<td class="td-hash" title="{_h(signer_did)}">{_h(did_short)}</td>'
            f'<td class="td-hash">{_h(_short_hash(eh))}</td>'
            f'<td class="td-hash">{_h(_short_hash(prev_hash))}</td>'
            f'<td class="td-hash">{_h(corrects_nid)}</td>'
            f'</tr>'
        )

    # ── Integrity notes ──────────────────────────────────────
    signed_count   = sum(1 for n in nodes if n.get("meta",{}).get("signature_status") == "mock_valid")
    unsigned_count = sum(1 for n in nodes if n.get("meta",{}).get("signature_status") == "unsigned")
    invalid_count  = sum(1 for n in nodes if n.get("meta",{}).get("signature_status") == "mock_invalid")

    def integrity_html() -> str:
        items = []
        items.append(f'<div class="integrity-item ok">✓ {total} events across {len(set(n["table"] for n in nodes))} table(s)</div>')
        if corr_count:
            items.append(f'<div class="integrity-item warn">↩ {corr_count} correction event(s) — originals preserved in log</div>')
        if len(chain_edges):
            items.append(f'<div class="integrity-item ok">✓ {len(chain_edges)} hash-chain link(s) detected</div>')
        if len(corr_edges):
            items.append(f'<div class="integrity-item warn">╌ {len(corr_edges)} correction edge(s) in graph</div>')
        if danger_count:
            items.append(f'<div class="integrity-item err">🛑 {danger_count} danger node(s) — dignity or execution breach</div>')
        else:
            items.append(f'<div class="integrity-item ok">✓ No dignity violations detected</div>')
        # Signature summary
        if signed_count:
            items.append(f'<div class="integrity-item ok">✓ {signed_count} event(s) with valid mock signature</div>')
        if unsigned_count:
            items.append(f'<div class="integrity-item warn">○ {unsigned_count} event(s) unsigned (allowed)</div>')
        if invalid_count:
            items.append(f'<div class="integrity-item err">✗ {invalid_count} event(s) with INVALID signature — possible tampering</div>')
        items.append(f'<div class="integrity-item ok">✓ No external scripts or stylesheets loaded</div>')
        items.append(f'<div class="integrity-item ok">✓ No network communication performed</div>')
        return "\n".join(items)

    # ── Final result badge ───────────────────────────────────
    RESULT_COLOR = {
        "success":                   "var(--green)",
        "partial_success":           "var(--amber)",
        "failed":                    "var(--red)",
        "unexpected_outcome":        "var(--red)",
        "dignity_violation_detected":"var(--red)",
        "in progress":               "var(--muted)",
    }
    result_color = RESULT_COLOR.get(final_result, "var(--muted)")

    # ── Assemble HTML ────────────────────────────────────────
    tl_items_html  = "\n".join(tl_item(i+1, n) for i, n in enumerate(nodes))
    table_rows_html= "\n".join(table_row(i+1, n) for i, n in enumerate(nodes))

    danger_banner = ""
    if danger_count:
        danger_banner = (
            '<div class="warn-banner">'
            '🛑 DIGNITY VIOLATION DETECTED — automated processing halted — '
            f'{danger_count} danger node(s) in this graph'
            '</div>'
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Dan-Go Negotiation Graph — {_h(claim_id)}</title>
<style>
{_INLINE_CSS}
</style>
</head>
<body>

<header class="page-header">
  <h1>Dan-Go Negotiation Graph — {_h(claim_id)}</h1>
  <span class="subtitle">dango-gitsea-bridge / su-table · generated {_h(gen_ts)}</span>
</header>

{danger_banner}

<div class="container">

<!-- ── SUMMARY ─────────────────────────────────── -->
<section>
  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="stat-card">
      <div class="val">{total}</div>
      <div class="lbl">Total Events</div>
    </div>
    <div class="stat-card {'danger' if danger_count else 'good'}">
      <div class="val" style="color:{_h(result_color)}">{_h(final_result.replace('_',' ').title())}</div>
      <div class="lbl">Final Result</div>
    </div>
    <div class="stat-card {'amber' if corr_count else ''}">
      <div class="val">{corr_count}</div>
      <div class="lbl">Corrections</div>
    </div>
    <div class="stat-card">
      <div class="val">{contrib_count}</div>
      <div class="lbl">Contributions</div>
    </div>
    <div class="stat-card {'danger' if danger_count else ''}">
      <div class="val">{danger_count}</div>
      <div class="lbl">Dignity Violations</div>
    </div>
    <div class="stat-card {'good' if signed_preview else ''}">
      <div class="val">{signed_preview}</div>
      <div class="lbl">Signed Events</div>
    </div>
  </div>
</section>

<!-- ── TIMELINE ─────────────────────────────────── -->
<section>
  <h2>Event Timeline</h2>
  <ul class="timeline">
{tl_items_html}
  </ul>
</section>

<!-- ── MERMAID SOURCE ────────────────────────────── -->
<section>
  <h2>Mermaid Source</h2>
  <div class="mermaid-wrap">
    <div class="mermaid-toolbar">
      <span class="toolbar-left">flowchart TD · {total} nodes · {len(edges)} edges</span>
      <button class="copy-btn" id="copy-btn" onclick="copyMermaid()">Copy</button>
    </div>
    <div class="mermaid-hint">
      Paste into <strong>mermaid.live</strong> to render the graph visually.
      This file loads no external scripts — rendering is your choice, not ours.
    </div>
    <pre class="mermaid-src"><code id="mermaid-source">{_h(mermaid_src)}</code></pre>
  </div>
</section>

<!-- ── EVENT TABLE ───────────────────────────────── -->
<section>
  <h2>Event Table</h2>
  <div class="event-table-wrap">
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>table</th>
          <th>event_type</th>
          <th>speaker / contributor</th>
          <th>timestamp</th>
          <th>summary</th>
          <th>signature</th>
          <th>signer did</th>
          <th>event_hash</th>
          <th>prev_hash</th>
          <th>corrects</th>
        </tr>
      </thead>
      <tbody>
{table_rows_html}
      </tbody>
    </table>
  </div>
</section>

<!-- ── INTEGRITY NOTES ───────────────────────────── -->
<section>
  <h2>Integrity Notes</h2>
  <div class="integrity-block">
{integrity_html()}
  </div>
</section>

</div><!-- /container -->

<footer class="page-footer">
  dango-gitsea-bridge · su-table append-only log ·
  claim_id: {_h(claim_id)} ·
  {_h(gen_ts)} ·
  No external dependencies. No network communication.
</footer>

<script>
{_COPY_SCRIPT}
</script>

</body>
</html>"""

    return html


# ══════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Export a su-table negotiation graph to mermaid, text, or HTML",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python runtime/graph_export.py --claim-id housing-001 --format text
  python runtime/graph_export.py --claim-id housing-001 --format mermaid
  python runtime/graph_export.py --claim-id housing-001 --format mermaid > examples/housing-001.graph.mmd
  python runtime/graph_export.py --claim-id housing-001 --format html --output examples/housing-001.graph.html
  python runtime/graph_export.py --list
        """,
    )
    p.add_argument("--claim-id", metavar="ID",
                   help="Claim ID to visualize")
    p.add_argument("--format",   choices=["mermaid", "text", "html"], default="text",
                   help="Output format (default: text)")
    p.add_argument("--output",   metavar="FILE",
                   help="Write output to FILE instead of stdout (required for --format html if piping)")
    p.add_argument("--list",     action="store_true",
                   help="List all available claim_ids in the su-table")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.list:
        ids = list_claim_ids()
        if not ids:
            print("No claim_ids found in su-table.")
        else:
            print("Available claim_ids in su-table:")
            for cid in ids:
                print(f"  {cid}")
        return

    if not args.claim_id:
        print("Error: --claim-id is required (or use --list)", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(args.claim_id)

    if not graph["nodes"]:
        print(f"No events found for claim_id: {args.claim_id}", file=sys.stderr)
        sys.exit(1)

    match args.format:
        case "mermaid":
            content = export_mermaid(graph)
        case "text":
            content = export_text(graph)
        case "html":
            content = export_html(graph)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"✓ Written to {out_path}", file=sys.stderr)
        if args.format == "html":
            print(f"  Open in browser: file://{out_path.resolve()}", file=sys.stderr)
    else:
        print(content)


if __name__ == "__main__":
    main()
